### ISSUE TITLE
Image blinked when setstate or listview is growing

### ISSUE THREAD

**Issue by Robihamanto** [Gabanelli/dynamic_url_image_cache#1]
Hi, this is really fixing the issue `Connection closed before full header was received` on Flutter.

However, when I use this package, it works perfectly but all images are blinked when I update the list item because of pagination.

I will continue to use this if the blinks issue is fixed.

Thank you 🙂

**Comment by Gabanelli** [comment]
Hi, thanks for the feedback, I'll investigate it

**Comment by Robihamanto** [comment]
> Hi, thanks for the feedback, I'll investigate it

This is really good work!

Also please consider adding `cacheWidth: double,
  cacheHeight: double,` to solve memory issues when loading the image from the network.
Thanks 👏🏻

**Comment by sandun-madushanka** [comment]
Is someone able to fix this issue?
This library is very useful. 
Thank you

**Comment by Gabanelli** [comment]
@Robihamanto I'm sorry for answering so late
About your problem, you can try to use ```gaplessPlayback``` property in your Image widget, as the example below:

```dart
Image(
  gaplessPlayback: true,
  image: DynamicUrlImageCache(
    imageId: 'imageId',
    imageUrl: 'imageUrl',
  ),
),
```

I'm working in use dynamic_url_image_cache along with cached_network_image, this could be helpful to avoid future issues.
